@startuml

package "slf4j" {
  interface Logger
  interface ILoggerFactory
}

package "org.logevents" {

	class LoggerDelegator implements Logger {
	  levelThreshold : Level|"Inherit"
	  ownObserver : LogEventObserver
	  inheritParentObserver : boolean
	}
	
	class LogEventFactory implements ILoggerFactory {
	  setLogLevel(logger, level)
	  setLogEventObserver(logger, observer, inheritParent)
	  addObserver(logger, observer)
	}
	
	interface LogEventGenerator
	LoggerDelegator ..> LogEventGenerator
	
	class NullLogEventGenerator implements LogEventGenerator
	class LevelLoggingEventGenerator implements LogEventGenerator
	
	interface LogEventObserver {
	  name
	  configure(Properties)
	  logEvent(e)
	}
	LevelLoggingEventGenerator ..> LogEventObserver
	
	class CompositeLogEventObserver implements LogEventObserver
	class ConditionalLogEventObserver implements LogEventObserver
	class BatchingLogEventObserver implements LogEventObserver {
	  idleTime
	  cooldownTime
	  maximumWaitTime
	}
	class CircularBufferLogEventDestination implements LogEventObserver
	class FileLogEventObserver implements LogEventObserver
	class ConsoleLogEventObserver implements LogEventObserver
	CompositeLogEventObserver ..> "*" LogEventObserver
	ConditionalLogEventObserver ..> "1" LogEventObserver
	
	
	package "formatting" {
		interface LogEventFormatter
		FileLogEventObserver ..> LogEventFormatter
		ConsoleLogEventObserver ..> LogEventFormatter
        class PatternFormatter implements LogEventFormatter
        class TTLLFormatter implements LogEventFormatter
	}
	
	class LogEventBatchProcessor
	BatchingLogEventObserver ..> LogEventBatchProcessor

}
	
@enduml
