@startuml

package "slf4j" {
  interface Logger
  interface ILoggerFactory
}

package "org.logevents" {

	class LoggerDelegator implements Logger
	
	class LogEventFactory implements ILoggerFactory
		
	interface LogEventObserver {
	  logEvent(e)
	}
	LoggerDelegator ..> LogEventObserver
	
	class CompositeLogEventObserver implements LogEventObserver
	class ConditionalLogEventObserver implements LogEventObserver
	class FileLogEventObserver implements LogEventObserver
	CompositeLogEventObserver ..> "*" LogEventObserver
	ConditionalLogEventObserver ..> "1" LogEventObserver
	
	
	package "formatting" {
		interface LogEventFormatter
		FileLogEventObserver ..> LogEventFormatter
		class PatternFormatter implements LogEventFormatter
        class TTLLFormatter implements LogEventFormatter
	}
	
}
	
@enduml
