@startuml

title Simple Object Diagram

object MyLogger
object CompositeObserver
object ConditionalObserver
object file
object console
object ConsoleDestination
object FileDestination

MyLogger -- CompositeObserver
CompositeObserver o-- ConditionalObserver
CompositeObserver o-- file
ConditionalObserver o-- console
console o-- ConsoleDestination
file o-- FileDestination

FileDestination : filename = "application.log"
ConditionalObserver : level = WARN


@enduml