@startuml

title Simple Object Diagram

object MyLogger
object CompositeObserver
object ConditionalObserver
object file
object console
object ConsoleObserver
object FileObserver

MyLogger -- CompositeObserver
CompositeObserver o-- ConditionalObserver
CompositeObserver o-- file
ConditionalObserver o-- console
console o-- ConsoleObserver
file o-- FileObserver

FileObserver : filename = "application.log"
ConditionalObserver : level = WARN


@enduml